

## name:     Catppuccin Kitty Mocha
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!


# OS Window titlebar colors
wayland_titlebar_color system

#font
 font_family JetBrainsMono Nerd Font
 font_size 11
# # The basic colors

 foreground               #CAD3F4
 background               #161420
 selection_foreground     #e0def4
 selection_background     #403d52

# background_opacity 0.9
 enable_background_blur yes
 background_blur 1


# Cursor colors
 cursor                  #F5E0DC
 cursor_text_color       #1E1E2E

#
# cursor                   #F5E0DC
# cursor_text_color        #e0def4
#
url_color                #c4a7e7

active_tab_foreground    #e0def4
active_tab_background    #26233a
inactive_tab_foreground  #6e6a86
inactive_tab_background  #191724

active_border_color      #31748f
inactive_border_color    #403d52

 # # The 16 terminal colors
*background:	#1A2026
*foreground:	#FFFFFF
*cursorColor:	#FFFFFF
*color0:	#242D35
*color1:	#FB6396
*color2:	#94CF95
*color3:	#F692B2
*color4:	#6EC1D6
*color5:	#CD84C8
*color6:	#7FE4D2
*color7:	#FFFFFF
*color8:	#526170
*color9:	#F92D72
*color10:	#6CCB6E
*color11:	#F26190
*color12:	#4CB9D6
*color13:	#C269BC
*color14:	#58D6BF
*color15:	#F4F5F2

# # black
 # color0   #26233a
 # color8   #6e6a86
 #
 # # red
 # color1   #eb6f92
 # color9   #eb6f92
 #
 # # green
 # color2  #A6E3A1
 # color10 #A6E3A1
 #
 #
 # # yellow
 # color3   #f6c177
 # color11  #f6c177
 #
 # # blue
 # color4   #9ccfd8
 # color12  #9ccfd8
 #
 # # magenta 
 # color5  #F5C2E7
 # color13 #F5C2E7
 #
 # # cyan
 # color6   #ebbcba
 # color14  #ebbcba
 #
 # # white
 # color7  #CDD6F4
 # color15 #A1A8C9 
 #
# mouse
open_url_with zen-browser
copy_on_select yes

# cursor
# cursor_shape underline
# shell_integration no-cursor
#
# window settings
remember_window_size no
window_padding_width 15
confirm_os_window_close 0
